<?php

return [
    'TYPE_ITEM_IDENTIFICATION' => env('TYPE_ITEM_IDENTIFICATION', 4),
    'FREE_OF_CHARGE_INDICATOR' => env('FREE_OF_CHARGE_INDICATOR', false),
    'TYPE_DOCUMENT_CREDIT_NOTE' => env('TYPE_DOCUMENT_CREDIT_NOTE', 4), // para cuando sea una nota crédito
    'TYPE_ORGANIZATION_JUR' => env('TYPE_ORGANIZATION_JUR', 1),
    'TYPE_ORGANIZATION_NAT' => env('TYPE_ORGANIZATION_NAT', 2),
    'MERCHANT_REGISTRATION' => env('MERCHANT_REGISTRATION', "0000-00"),
    'PREVIOUS_BALANCE' => env('PREVIOUS_BALANCE', 0),
    'PAYMENT_METHOD_EF' => env('PAYMENT_METHOD_EF', 10),
    'PAYMENT_FORM_EF' => env('PAYMENT_FORM_EF', 1),
    'PAYMENT_METHOD_CR' => env('PAYMENT_METHOD_CR', 30),
    'PAYMENT_FORM_CR' => env('PAYMENT_FORM_CR', 2),
    'TAX' => env('TAX', 1),
    'ALLOWANCE_CHARGES_DISCOUNT' => env('ALLOWANCE_CHARGES_DISCOUNT', 12),
    'ALLOWANCE_CHARGES_INDICATOR' => env('ALLOWANCE_CHARGES_INDICATOR', false),
    'ALLOWANCE_CHARGES_REASON' => env('ALLOWANCE_CHARGES_REASON', "Descuento General"),
    'UNIT_MEASURE' => env('UNIT_MEASURE', 70),
    'SYNC_DIAN' => env('SYNC_DIAN', 1),
    'API_DIAN' => env('API_DIAN', "https://facturaconmiggo.com/api/ubl2.1/"),
    'DURATION_MEASURE' => env('DURATION_MEASURE', 30),
    'DIAN_ESTADO_ERROR' => env('DIAN_ESTADO_ERROR', 3),
    'DIAN_ESTADO_PROCESANDO' => env('DIAN_ESTADO_PROCESANDO', 4),
    'DIAN_ESTADO_PENDIENTE_VALIDAR' => env('DIAN_ESTADO_PENDIENTE_VALIDAR', 5),
    'DIAN_ESTADO_SINCRONIZADA' => env('DIAN_ESTADO_SINCRONIZADA', 6),
    'MENSAJE_ERROR' => env('MENSAJE_ERROR', "Uno de los parámetros no es un array procesable"),
];